/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fileops.h"

bool_t
xdr_file_data(xdrs, objp)
	XDR *xdrs;
	file_data *objp;
{

	if (!xdr_string(xdrs, &objp->fname, MAXNAMELEN))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->content, MAXDATALEN))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_op_result(xdrs, objp)
	XDR *xdrs;
	op_result *objp;
{

	if (!xdr_int(xdrs, &objp->status))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->message, 256))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_read_result(xdrs, objp)
	XDR *xdrs;
	read_result *objp;
{

	if (!xdr_int(xdrs, &objp->status))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->content, MAXDATALEN))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_list_result(xdrs, objp)
	XDR *xdrs;
	list_result *objp;
{

	if (!xdr_int(xdrs, &objp->status))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->files, MAXDATALEN))
		return (FALSE);
	return (TRUE);
}
