/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILEOPS_H_RPCGEN
#define _FILEOPS_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define MAXNAMELEN 256
#define MAXDATALEN 65536

struct file_data {
	char *fname;
	char *content;
};
typedef struct file_data file_data;
#ifdef __cplusplus
extern "C" bool_t xdr_file_data(XDR *, file_data*);
#elif __STDC__
extern  bool_t xdr_file_data(XDR *, file_data*);
#else /* Old Style C */
bool_t xdr_file_data();
#endif /* Old Style C */


struct op_result {
	int status;
	char *message;
};
typedef struct op_result op_result;
#ifdef __cplusplus
extern "C" bool_t xdr_op_result(XDR *, op_result*);
#elif __STDC__
extern  bool_t xdr_op_result(XDR *, op_result*);
#else /* Old Style C */
bool_t xdr_op_result();
#endif /* Old Style C */


struct read_result {
	int status;
	char *content;
};
typedef struct read_result read_result;
#ifdef __cplusplus
extern "C" bool_t xdr_read_result(XDR *, read_result*);
#elif __STDC__
extern  bool_t xdr_read_result(XDR *, read_result*);
#else /* Old Style C */
bool_t xdr_read_result();
#endif /* Old Style C */


struct list_result {
	int status;
	char *files;
};
typedef struct list_result list_result;
#ifdef __cplusplus
extern "C" bool_t xdr_list_result(XDR *, list_result*);
#elif __STDC__
extern  bool_t xdr_list_result(XDR *, list_result*);
#else /* Old Style C */
bool_t xdr_list_result();
#endif /* Old Style C */


#define FILEPROG ((rpc_uint)0x31000099)
#define FILEVERS ((rpc_uint)1)

#ifdef __cplusplus
#define CREATE_FILE ((rpc_uint)1)
extern "C" op_result * create_file_1(char **, CLIENT *);
extern "C" op_result * create_file_1_svc(char **, struct svc_req *);
#define WRITE_FILE ((rpc_uint)2)
extern "C" op_result * write_file_1(file_data *, CLIENT *);
extern "C" op_result * write_file_1_svc(file_data *, struct svc_req *);
#define APPEND_FILE ((rpc_uint)3)
extern "C" op_result * append_file_1(file_data *, CLIENT *);
extern "C" op_result * append_file_1_svc(file_data *, struct svc_req *);
#define READ_FILE ((rpc_uint)4)
extern "C" read_result * read_file_1(char **, CLIENT *);
extern "C" read_result * read_file_1_svc(char **, struct svc_req *);
#define DELETE_FILE ((rpc_uint)5)
extern "C" op_result * delete_file_1(char **, CLIENT *);
extern "C" op_result * delete_file_1_svc(char **, struct svc_req *);
#define UPLOAD_FILE ((rpc_uint)6)
extern "C" op_result * upload_file_1(file_data *, CLIENT *);
extern "C" op_result * upload_file_1_svc(file_data *, struct svc_req *);
#define DOWNLOAD_FILE ((rpc_uint)7)
extern "C" read_result * download_file_1(char **, CLIENT *);
extern "C" read_result * download_file_1_svc(char **, struct svc_req *);
#define LIST_FILES ((rpc_uint)8)
extern "C" list_result * list_files_1(void *, CLIENT *);
extern "C" list_result * list_files_1_svc(void *, struct svc_req *);

#elif __STDC__
#define CREATE_FILE ((rpc_uint)1)
extern  op_result * create_file_1(char **, CLIENT *);
extern  op_result * create_file_1_svc(char **, struct svc_req *);
#define WRITE_FILE ((rpc_uint)2)
extern  op_result * write_file_1(file_data *, CLIENT *);
extern  op_result * write_file_1_svc(file_data *, struct svc_req *);
#define APPEND_FILE ((rpc_uint)3)
extern  op_result * append_file_1(file_data *, CLIENT *);
extern  op_result * append_file_1_svc(file_data *, struct svc_req *);
#define READ_FILE ((rpc_uint)4)
extern  read_result * read_file_1(char **, CLIENT *);
extern  read_result * read_file_1_svc(char **, struct svc_req *);
#define DELETE_FILE ((rpc_uint)5)
extern  op_result * delete_file_1(char **, CLIENT *);
extern  op_result * delete_file_1_svc(char **, struct svc_req *);
#define UPLOAD_FILE ((rpc_uint)6)
extern  op_result * upload_file_1(file_data *, CLIENT *);
extern  op_result * upload_file_1_svc(file_data *, struct svc_req *);
#define DOWNLOAD_FILE ((rpc_uint)7)
extern  read_result * download_file_1(char **, CLIENT *);
extern  read_result * download_file_1_svc(char **, struct svc_req *);
#define LIST_FILES ((rpc_uint)8)
extern  list_result * list_files_1(void *, CLIENT *);
extern  list_result * list_files_1_svc(void *, struct svc_req *);

#else /* Old Style C */
#define CREATE_FILE ((rpc_uint)1)
extern  op_result * create_file_1();
extern  op_result * create_file_1_svc();
#define WRITE_FILE ((rpc_uint)2)
extern  op_result * write_file_1();
extern  op_result * write_file_1_svc();
#define APPEND_FILE ((rpc_uint)3)
extern  op_result * append_file_1();
extern  op_result * append_file_1_svc();
#define READ_FILE ((rpc_uint)4)
extern  read_result * read_file_1();
extern  read_result * read_file_1_svc();
#define DELETE_FILE ((rpc_uint)5)
extern  op_result * delete_file_1();
extern  op_result * delete_file_1_svc();
#define UPLOAD_FILE ((rpc_uint)6)
extern  op_result * upload_file_1();
extern  op_result * upload_file_1_svc();
#define DOWNLOAD_FILE ((rpc_uint)7)
extern  read_result * download_file_1();
extern  read_result * download_file_1_svc();
#define LIST_FILES ((rpc_uint)8)
extern  list_result * list_files_1();
extern  list_result * list_files_1_svc();
#endif /* Old Style C */

#endif /* !_FILEOPS_H_RPCGEN */
