/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fileops.h"

op_result *
create_file_1(argp, rqstp)
	char **argp;
	struct svc_req *rqstp;
{

	static op_result  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

op_result *
write_file_1(argp, rqstp)
	file_data *argp;
	struct svc_req *rqstp;
{

	static op_result  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

op_result *
append_file_1(argp, rqstp)
	file_data *argp;
	struct svc_req *rqstp;
{

	static op_result  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

read_result *
read_file_1(argp, rqstp)
	char **argp;
	struct svc_req *rqstp;
{

	static read_result  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

op_result *
delete_file_1(argp, rqstp)
	char **argp;
	struct svc_req *rqstp;
{

	static op_result  result;

	/*
	 * insert server code here
	 */

	return(&result);
}
