/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fileops.h"


void
fileprog_1(host)
char *host;
{
	CLIENT *clnt;
	op_result  *result_1;
	char * create_file_1_arg;
	op_result  *result_2;
	file_data  write_file_1_arg;
	op_result  *result_3;
	file_data  append_file_1_arg;
	read_result  *result_4;
	char * read_file_1_arg;
	op_result  *result_5;
	char * delete_file_1_arg;
	clnt = clnt_create(host, FILEPROG, FILEVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = create_file_1(&create_file_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_2 = write_file_1(&write_file_1_arg, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_3 = append_file_1(&append_file_1_arg, clnt);
	if (result_3 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_4 = read_file_1(&read_file_1_arg, clnt);
	if (result_4 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_5 = delete_file_1(&delete_file_1_arg, clnt);
	if (result_5 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );
}


main(argc, argv)
int argc;
char *argv[];
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	fileprog_1( host );
}
