/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fileops.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

op_result *
create_file_1(argp, clnt)
	char **argp;
	CLIENT *clnt;
{
	static op_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, CREATE_FILE, xdr_wrapstring, argp, xdr_op_result, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

op_result *
write_file_1(argp, clnt)
	file_data *argp;
	CLIENT *clnt;
{
	static op_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, WRITE_FILE, xdr_file_data, argp, xdr_op_result, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

op_result *
append_file_1(argp, clnt)
	file_data *argp;
	CLIENT *clnt;
{
	static op_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, APPEND_FILE, xdr_file_data, argp, xdr_op_result, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

read_result *
read_file_1(argp, clnt)
	char **argp;
	CLIENT *clnt;
{
	static read_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, READ_FILE, xdr_wrapstring, argp, xdr_read_result, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

op_result *
delete_file_1(argp, clnt)
	char **argp;
	CLIENT *clnt;
{
	static op_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, DELETE_FILE, xdr_wrapstring, argp, xdr_op_result, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

op_result *
upload_file_1(argp, clnt)
	file_data *argp;
	CLIENT *clnt;
{
	static op_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, UPLOAD_FILE, xdr_file_data, argp, xdr_op_result, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

read_result *
download_file_1(argp, clnt)
	char **argp;
	CLIENT *clnt;
{
	static read_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, DOWNLOAD_FILE, xdr_wrapstring, argp, xdr_read_result, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

list_result *
list_files_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static list_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, LIST_FILES, xdr_void, argp, xdr_list_result, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
